### ISSUE TITLE
Get webcams and test streaming on JTV

### ISSUE THREAD

**Issue by delroth** [prologin/sadm#11]
> ###### Originally posted 2012-01-11 22:30 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

We should get some webcams and test a good streaming setup to send our stream to a service like justin.tv (probably the best right now).

**Comment by seirl** [comment]
> ###### Originally posted 2013-07-22 11:43 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Done this year, wasn't really interesting...
