### ISSUE TITLE
Automate xsessions order

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#113]
To reorder the xsessions, we usually rename the files in /usr/share/xsessions to match the order we want, and disable the ones we don't want:

```
$ ls /usr/share/xsessions/
01-gnome-xorg.desktop
02-plasma.desktop
03-i3.desktop
04-xfce.desktop
99-awesome.desktop
gnome-classic.desktop.disabled
gnome.desktop.disabled
i3-with-shmlog.desktop.disabled
```

We also disable the wayland sessions:

```
$ ls /usr/share/wayland-sessions/
gnome.desktop.disabled
```

This should be automated.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/113
