### ISSUE TITLE
Handle primary key updates in the synchronisation library

### ISSUE THREAD

**Issue by pmderodat** [prologin/sadm#12]
> ###### Originally posted 2013-05-08 17:07 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

The synchronisation library should handle updates that modify an entity’s primary key. This should requires to change the format of updates to specify the old and the new primary key (currently, an update contains only a single dictionnary of all up-to-date fields).

**Comment by seirl** [comment]
> ###### Originally posted 2013-09-14 00:56 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

A primary key shouldn't be updated. We could use unique IDs as primary keys instead of having a special case for primary keys update (which could interact badly with other services such as redmine).
