### ISSUE TITLE
let hfs be stateless

### ISSUE THREAD

**Issue by multun** [prologin/sadm#121]
hfs holds a list of currently running nbd servers

**Comment by multun** [comment]
how about listing all nbd-servers on each home request, instead of relying on the internal mapping ?
currently, restarting the hfs server makes it spawn new processes serving the same file, which may not be ok ?

**Comment by seirl** [comment]
As discussed on IRC, it is more reliable to have the HFS be parents of the nbd processes, so that the nbd mounts are killed when the HFS service dies. That way we can never lose track of processes, and two machines will not be able to mount the same HFS.
