### ISSUE TITLE
rfs/tarball-homes.sh is stupid af

### ISSUE THREAD

**Issue by multun** [prologin/sadm#122]
it deletes files instead of excluding these from a rsync run

**Comment by Hatrix42** [comment]
I guess this issue can be closed because of this? https://github.com/prologin/sadm/commit/cd422ac424519beae4a358b7a590243c77814773

**Comment by multun** [comment]
nop, it needs a replacement (I may be wrong)

**Comment by Zopieux** [comment]
@multun You pushed a new version of your script right? Can you close?

**Comment by Zopieux** [comment]
Added in 0a0947de8b570d5663b325fcb98f5ea1fe9594c5: https://github.com/prologin/sadm/blob/master/rfs/homes_backup.sh
