### ISSUE TITLE
No offline docs and IDE for C#

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#123]

**Comment by Zopieux** [comment]
Would Visual Studio Code (electron, atom-like) work?

**Comment by seirl** [comment]
https://www.monodevelop.com/

**Comment by Fumesover** [comment]
Instead of adding a new IDE, it could be better to install a package to atom in order to support C# ?
It coult be something like `omnisharp-atom` with `ide-csharp` and `language-csharp` i think

**Comment by Marcerisson** [comment]
@Fumesover yes it could be a solution. Things to be checked in order to use this method : ability to use autocompletion, syntax checking and building and running from inside Atom

**Comment by seirl** [comment]
There's no problem in adding an IDE, we'll just add monodevelop. The main problem here is for offline docs. We need to find somewhere to download an html build of those docs.

**Comment by cafehaine** [comment]
https://blogs.msdn.microsoft.com/pakistan/2013/02/04/download-all-msdn-documentations-for-offline-access/
There must be a way to extract those downloaded help files

**Comment by Marcerisson** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/
PDFs that could be used as documentation for c# are available for download at those addresses

**Comment by Zopieux** [comment]
Wesh. https://github.com/dotnet/docs

**Comment by Marcerisson** [comment]
An IDE is already installed. Check [a28a748a](https://github.com/prologin/sadm/commit/a28a748a0db63ebd7aff4c6e3523ee03f4623a2f)

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/123
