### ISSUE TITLE
HFS does not auto reconnect to Postgres

### ISSUE THREAD

**Issue by delroth** [prologin/sadm#13]
> ###### Originally posted 2013-05-16 21:44 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

This caused an outage in the middle of the night during the 2013 finals. As this is a fairly low traffic application, a fix could be to open and close the connection for each HFS request. This was done successfully during the finals but not committed.

**Comment by seirl** [comment]
> ###### Originally posted 2013-05-17 13:32 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Fixed by 2fc0ea8.
