### ISSUE TITLE
Allow HFS restart without killing NBD connections

### ISSUE THREAD

**Issue by delroth** [prologin/sadm#14]
> ###### Originally posted 2013-05-16 21:45 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

Killing NBD connections basically requires a full restart of the user machines connected to these NBDs. When we needed to restart the HFS daemons (only once) we had to get everyone to leave the room and disconnect. Not ideal.

**Comment by seirl** [comment]
> ###### Originally posted 2013-07-22 11:42 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Since 2fc0ea8, the hfs reconnects to the DB at each http query, this should not happen anymore.
