### ISSUE TITLE
Improve the finals website

### ISSUE THREAD

**Issue by delroth** [prologin/sadm#15]
> ###### Originally posted 2013-05-16 21:46 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

* Switch to english in the code (models name, etc.)
* Fix some Python 3 stuff (__unicode__)
* Document deployment

**Comment by seirl** [comment]
> ###### Originally posted 2013-08-02 08:46 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

* Models names are already in english
* Python3 encoding problems have been fixed by 19f3df9 and 29ba775
