### ISSUE TITLE
disable suspend

### ISSUE THREAD

**Issue by multun** [prologin/sadm#154]
suspending machines leads to nbd-server exiting => oops

**Comment by Zopieux** [comment]
https://wiki.debian.org/Suspend#Disable_suspend_and_hibernation

**Comment by Zopieux** [comment]
One also has to disable auto-suspend in the various desktop environments (Gnome).

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/154
