### ISSUE TITLE
Centralized announce system (IRC #announce + zenity)

### ISSUE THREAD

**Issue by zopieux** [prologin/sadm#157]
It would be cool  to have a script that can send an announce on both people's machine (xrun + zenity) and the IRC channel. A even more kikoo feature would be a TTS on the radio.

**Comment by seirl** [comment]
+ log everything on an HTML page

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/157
