### ISSUE TITLE
Warn when no champions are available in a tournament

### ISSUE THREAD

**Issue by multun** [prologin/sadm#159]
Champions can be deleted. When all are gone, the tournament doesn't include the contestant.

**Comment by seirl** [comment]
I think this is WONTFIX, contestants usually delete their champions for a reason, no need for organizers to be warned about it.

**Comment by O-Xian** [comment]
It could still be interesting to have all the contestants included in the final tournament's results, so that we have a full list at the end and all can receive their diploma.
