### ISSUE TITLE
Automatic line break in the notify bot

### ISSUE THREAD

**Issue by delroth** [prologin/sadm#16]
> ###### Originally posted 2013-05-16 21:47 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

Having to type the line breaks manually is error prone and annoying.

**Comment by seirl** [comment]
> ###### Originally posted 2013-05-18 11:50 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Fixed by adfcea3.
