### ISSUE TITLE
Write tools and automation for Wake on Lan

### ISSUE THREAD

**Issue by Zopieux** [prologin/sadm#160]
All machines are WoL-enabled. We know their MACs with mdb. It would be cool to have tooling to:

* boot everything
* auto-boot machines shutdown by contestants

**Comment by seirl** [comment]
Since be81a0f62b880c5afebc3035900f18a91cb05d18, booting all the machines in a room is as trivial as:

    ansible pasteur -m wakeonlan -a "mac={{ mac }}"
