### ISSUE TITLE
Move all Django apps from gunicorn to Tornado

### ISSUE THREAD

**Issue by delroth** [prologin/sadm#17]
> ###### Originally posted 2013-05-16 21:48 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

That way it will be easier to move everything to a "standard" prologin.tornado module which will allow us to add features to all services at once.

**Comment by seirl** [comment]
> ###### Originally posted 2013-07-22 23:17 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

We decided to do this via a common WSGI interface, prologin.web.
