### ISSUE TITLE
Implement locks in udbsync_passwd 

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#170]
There is a race condition between udbsync_passwd updates and other utilities editing /etc/passwd (and friends).

I'm not aware of any standard locking of those files, but `useradd` does check for a `/etc/passwd.lock` file before editing it, same for shadow and group. udbsync_passwd should implement this.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/170
