### ISSUE TITLE
Rewrite the master/worker system

### ISSUE THREAD

**Issue by delroth** [prologin/sadm#18]
> ###### Originally posted 2013-05-16 21:49 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

Port to Python 3, get rid of gevent/xmlrpc in favor of tornado/http with some kind of rpc layer (todo: make that generic, with timeauth support), check if a port is available before using it, make the code less ugly, integrate with prologin.config, document, ...

**Comment by seirl** [comment]
> ###### Originally posted 2014-05-06 19:56 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Done.
