### ISSUE TITLE
Add an enable/disable setting for HTTP authentication

### ISSUE THREAD

**Issue by pmderodat** [prologin/sadm#19]
> ###### Originally posted 2013-05-25 13:01 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

For debugging purposes, it would be nice to be able to disable HTTP authentication (prologin.timeauth), so that making requests using curl would be easy again.

To be defined: would this setting be global (/etc/prologin/timeauth.yml) or local to each daemon/client?

**Comment by seirl** [comment]
> ###### Originally posted 2013-07-22 23:13 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Added in 8e51a50.
