### ISSUE TITLE
Ansible: automate steps when in and out of contest mode.

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#195]
These Ansible tasks should not only enable some stuff when in contest mode, they should also make sure to **disable them** outside of contest mode.

Done | Service | Base mode | Contest mode
---|---|---|---
| <ul><li>[x] </li></ul> | Concours | Nginx authentication with password | Open to everyone
| <ul><li>[x] </li></ul> | Wallpaper | Fetched from URL given by `wallpaper` inventory variable | Fetched from URL given by `wallpaper_contest` inventory variable
| <ul><li>[ ] </li></ul> | Login manager theme | Default Prologin theme | This year's theme
| <ul><li>[x] </li></ul> | prologin20XX package | `pacman: state=absent` | `pacman: state=present`
| <ul><li>[x] </li></ul> | `stechec2-generator` player environment in HFS Skeleton | `file: state=absent` | `file: state=present`
| <ul><li>[x] </li></ul> | Documentation in docs/ | `file: state=absent` | `file: state=present`
| <ul><li>[x] </li></ul> | Firewall | all users authorized | only organizers + roots
| <ul><li>[x] </li></ul> | HFS | using hfsdb, mounting from /export/hfs | using hfsdbcontest, mounting from /export/hfscontest

We should also tag all these tasks with a `contest_switch` tag so that we can reexecute them all at once without reexecuting all the playbooks.

**Comment by Zopieux** [comment]
prologin/lightdm-prologin-greeter@5074b73d0c4ba06f4cf47fe5f7179e8af33d2c76 should help for *Login manager theme*.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/195
