### ISSUE TITLE
Single Sign On

### ISSUE THREAD

**Issue by delroth** [prologin/sadm#2]
> ###### Originally posted 2012-01-10 01:17 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

~~Maybe use Kerberos/LDAP for that?~~

* ✔ openresty package with extra lua libs needed for sso
* ✔ `presencesync_cacheserver`
* ✔ docs
* ✔ real-life testing
* ✗ SSO on IRC (cc @Mareo)
* ✗ SSO on dj_ango (see #78)
* ✗ SSO on paste

**Comment by seirl** [comment]
> ###### Originally posted 2013-07-23 12:47 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

We're going to try web SSO using SSL client certs saved in UDB.

**Comment by audebert** [comment]
> ###### Originally posted 2015-02-08 21:13 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Kerberos/LDAP is maybe not the best if we want to keep prologin-sadm simple and stupid.

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-02 12:31 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

IP based authentication for django apps may be interesting:

- User goes to http://app/
- Django app does DNS reverse lookup to get hostname of the request originator
- Django app looks into udb to get the user logged into this hostname
- Django app authenticates this user

**Comment by delroth** [comment]
> ###### Originally posted 2015-04-02 12:50 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

FYI, you might want to investigate SSO solutions that require minimal application modifications so that you could get it to somewhat work with non-Django apps (if you limit to Django apps, having nice SSO is easy, I'm sure there are already premade apps for that).

For example, you could use openresty as the reverse proxy for web apps (nginx + lua, basically) and implement the SSO layer in there. That would allow you to pass a trusted X-User-Login header to applications and use that directly for auth.

In any case, limiting to Django apps really narrows the scope, and I'm not sure if we want this (what about Redmine or wiki for example?)

**Comment by delroth** [comment]
> ###### Originally posted 2015-04-02 12:51 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

As an example, googling for "openresty sso" gives me interesting results like https://github.com/Kloadut/SSOwat

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-11 13:09 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Started in 115533e. Needs a better cache in a standalone presencesync client.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-11 19:07 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

b494dc9 simplifies the lua scripts by putting lua libs into openresty. Stills need the presencesync cache, it's coming next.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-18 18:11 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

presencesync cache done, needs to update docs on installing & enabling it.
Also, bug: the sso/ folder is not installed in /etc/nginx by any install.py target!

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-18 21:52 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Some nginx & django stuff in pull request #8.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-25 12:39 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Mostly done now pull request #8 is merged. Will check the paste service before closing that.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-30 07:23 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Waiting for paste to be updated.

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-05-16 08:31 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

@Mareo started hacking around UnrealIRCd to add SSO support (auto oper/voice/channel protecion). Needs to be polished & fully integrated into setup (aka documented).
