### ISSUE TITLE
ansible: Migrate old integration/QA container tests to the new setup

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#205]
We used to have setup and QA tests interleaved in the container setup scripts. This approach doesn't work anymore because the setup is done through Ansible playbooks.

To get back feature parity, someone should go to `install_scripts/containers/old_scripts/`, look at all the tests we used to have, and split them in four categories:

- Tests that are now already asserted in a declarative fashion with ansible. Things like checking whether a service is active or whether a file is present. Testing this is redundant with the roles themselves, as explained [here](https://docs.ansible.com/ansible/latest/reference_appendices/test_strategies.html#the-right-level-of-testing). These tests should be **removed**.
- Tests that check that a service is working well on the surface. Things like checking whether a service we just started returns coherent information on a specific port. These tests should be **integrated to the ansible playbooks** like here: https://github.com/prologin/sadm/commit/0e17934639bad596858f18069834854fa8cb8feb
- Tests that require fake data, or running fake services. This one is harder and will require more thought on a case-by-case basis, as it might be problematic to have test data in prod, but sometimes it is desirable for live QA checks.

**Comment by audebert** [comment]
Proposed steps:

* Write test plan
* Implement test plan

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/205
