### ISSUE TITLE
udb: prevent people from creating a "root" user

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#207]
It's unlikely that people would be stupid enough to do that, but we should check regardless. Thanks to @Zopieux for finding out the issue.

**Comment by seirl** [comment]
Actually, we should probably also error out in udbsync_passwd when replacing users outside the managed range.

**Comment by Zopieux** [comment]
Apparently "Fixes issue #207" is not a good enough commit-message trigger.

**Comment by Zopieux** [comment]
As for `udbsync_passwd` safeguards, meh, I'd like to keep it simple. If I had to do it though, I'd skip over reserved ranges (ie. leave them as-is) and output a `logging.error` for each such skipped entry.
