### ISSUE TITLE
Ansible script or module to register machines & create users

### ISSUE THREAD

**Issue by zopieux** [prologin/sadm#214]
### Register machines

With `virt-install` it's super easy to create a VM with a given KVM mac address. To avoid having to interactively register it using PXE menus or using the http://mdb/ interface, I'd like to be able to run something like (basically invoking `manage.py addmachine` with defaults for rfs, hfs, mtype, room):

    $ <something> mdb add pas-r01p01 52:54:00:01:01:01 [optional aliases…]

### Create users

To do anything useful (incl. testing) once the container setup is done, a root/staff/contestant user must be created. Doing that with `manage.py batchimport` is slightly painful: it's meant for batch files and has too many flags to remember. I'd like to be able to run something lilke:

    $ <something> udb add --root admin pswd
    $ <something> udb add --staff seirl pswd

**Comment by seirl** [comment]
```
$ ANSIBLE_LIBRARY=library ansible gw -m mdb -a "hostname=lol mac=66:66:55:55:44:44 mtype=service room=pasteur"                      
gw | CHANGED => {
    "changed": true
}
```

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/214
