### ISSUE TITLE
Use the RPC system to query mdb/udb/...

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#22]
> ###### Originally posted 2013-09-14 00:48 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

This can be largely factorized as we already have timeauth support built in the RPC system.
This will likely be done with a tornado app wrapping the Django wsgi app.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-05-07 14:21 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

I see what you did there.

**Comment by seirl** [comment]
Mostly done in PR #84

**Comment by seirl** [comment]
Services that still need to use the rpc:

- `prologin.hfs.{client,server}`
- `prologin.presenced.{client,server}`
- `prologin.synchronisation`

This will obsolete `prologin.webapi`. After that, we can also use `aiohttp` for `prologin.netboot` to remove the dependency to `tornado` completely.

**Comment by Zopieux** [comment]
`prologin.presenced` is gone in branch `ansible-greeter`.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/22
