### ISSUE TITLE
Create some reusable vagrant/docker configs to deploy a test infra in VMs

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#24]
> ###### Originally posted 2013-09-14 00:50 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

**Comment by audebert** [comment]
> ###### Originally posted 2014-05-02 21:26 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

I will publish what I have setup. (currently stored in /sgoinfre/work/prologin)

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-08 14:22 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

See c306a46 and  https://bitbucket.org/halfr/prologin-sadm-libvirt
