### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#25]
> ###### Originally posted 2013-09-14 00:53 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

* Every service should respond on /__ping
* The services should export some graphed values and possibly alert the orgas
* Weathermap of the network?
* Machine monitoring (https://github.com/prometheus/node_exporter), web interface (https://github.com/prometheus/promdash) and aggregation of data (https://github.com/prometheus/prometheus).

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-08 23:22 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

For django services: https://github.com/korfuri/django-prometheus

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-22 01:11 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Work started at:

* https://bitbucket.org/halfr/sadm/commits/branch/monitoring
* https://bitbucket.org/halfr/prometheus-journald
* https://aur.archlinux.org/packages/prometheus-node-exporter/

**Comment by audebert** [comment]
> ###### Originally posted 2017-01-28 16:08 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Work done:

* Services export metrics to be collected by prometheus.

```
python-lib/prologin/concours/stechec/monitoring.py
python-lib/prologin/hfs/monitoring.py
python-lib/prologin/masternode/monitoring.py
python-lib/prologin/presencesync/monitoring.py
python-lib/prologin/rpc/monitoring.py
python-lib/prologin/workernode/monitoring.py
```

* The target url are documented in `etc/prometheus/prometheus.conf`.
* Documented in  `docs/source/monitoring.rst`

Work remaining:

* Update `docs/source/monitoring.rst` to use grafana instead of promdash. promdash is deprecated.
* Document alertmanager
* Add alerts

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/25
