### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#26]
> ###### Originally posted 2013-09-14 00:58 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

We must have unit tests for *all* services, instead of just deploying the whole infra to check if everything works properly.

**Comment by audebert** [comment]
> ###### Originally posted 2015-03-31 14:29 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Basic test procedures are being written in the docs. They must be performed by a human, but it's better than nothing.

**Comment by seirl** [comment]
> ###### Originally posted 2015-05-07 04:22 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

This issue is not precise enough. We have some tests for what can be tested easily, if more tests are needed we should do more specific issues.
