### ISSUE TITLE
Stream matches on a video projector

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#27]
> ###### Originally posted 2013-12-12 17:49 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Technically not resolved either :)

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-08 14:37 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Technically not an issue.

**Comment by delroth** [comment]
> ###### Originally posted 2015-04-08 20:38 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

Oops, modified the description, I'm stupid.

I meant to say: "Technically not resolved either :)". Issue trackers are pretty good at tracking feature requests too.

**Comment by seirl** [comment]
> ###### Originally posted 2015-05-07 04:20 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Done with 3a82658e1d06
