### ISSUE TITLE
Graph useless stuff

### ISSUE THREAD

**Issue by delroth** [prologin/sadm#3]
> ###### Originally posted 2012-01-10 01:18 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

* Number of matches currently running
* Number of people currently present in SM
* Used bandwidth
* Number of coffees served? :D

**Comment by prololo** [comment]
> ###### Originally posted 2012-01-10 01:20 by [prologin](https://bitbucket.org/prologin/) on Bitbucket

* Remaining mate bottles (if we manage to import some)

**Comment by delroth** [comment]
> ###### Originally posted 2012-01-10 01:25 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

Also, hook some user programs (make, for example) and display the number of compilations, number of edited files, mean time spent in vim, number of vim users vs number of emacs users, etc.

**Comment by audebert** [comment]
> ###### Originally posted 2012-04-22 16:35 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

- network monitoring: https://github.com/FremaksGmbH/c3netmon-public

**Comment by seirl** [comment]
> ###### Originally posted 2013-07-23 11:44 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

We could log stats on each match:

* Number of turns
* Number of {action} done by each participant
* Shortest match
* Match with the greatest number of {action}
...

**Comment by audebert** [comment]
> ###### Originally posted 2015-02-08 21:03 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

http://prometheus.io/ looks very promising

**Comment by seirl** [comment]
This is basically done with the grafana/prometheus setup. I filed https://github.com/prologin/stechec2/issues/42 for exporting match-specific info, we can open a new issue in sadm/ once this info is available.
