### ISSUE TITLE
concours: contestants should be able to read logs from their champions

### ISSUE THREAD

**Issue by pmderodat** [prologin/sadm#31]
> ###### Originally posted 2014-05-11 13:52 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

In the concours website, contestants can spawn matches involving their champions and others’ champions. However, they currently cannot read their champions’ logs from these matches, only organizers can.

Contestant A must not be able to read Contestant B’s champion logs, since it may contain relevant information about the champion (thus it would enable one to cheat!), but at least they should be able to read their own champions’ logs.

I’ve heard that this feature used to work before, so it should to fix it.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-29 07:07 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Isn't that already done? See [this permission check](https://bitbucket.org/prologin/sadm/src/44deb2eef7a7bd294445564201b47d5d7b71b176/python-lib/prologin/concours/stechec/templates/stechec/match-detail.html?at=master#cl-66) in match details.

**Comment by seirl** [comment]
> ###### Originally posted 2015-05-07 04:49 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

I just tried, it doesn't work.

**Comment by seirl** [comment]
> ###### Originally posted 2015-05-07 05:08 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Fixed by a2c1a3eb02f7
