### ISSUE TITLE
concours: contestants should be able to read server logs

### ISSUE THREAD

**Issue by pmderodat** [prologin/sadm#32]
> ###### Originally posted 2014-05-11 13:54 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

Because… why not? It is not directly useful to contestants, but it could help organizers to find out what went wrong when looking at a contestant’s screen.

This is assuming that stéchec server does not leak “sensible” information, but I guess it actually has no such thing to leak.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-29 07:09 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

If that's still relevant, this is a [one-line fix](https://bitbucket.org/prologin/sadm/src/44deb2eef7a7bd294445564201b47d5d7b71b176/python-lib/prologin/concours/stechec/templates/stechec/match-detail.html?at=master#cl-81).

**Comment by seirl** [comment]
> ###### Originally posted 2015-05-07 04:54 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Fixed by 7529da5
