### ISSUE TITLE
usermap: add a legend for user color

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#35]
> ###### Originally posted 2014-05-12 13:34 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Add a legend for the colors in the svg: python-lib/prologin/presencesync_clients/usermap.svg

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-05 20:12 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Assigning to me because it's included in #51.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/35
