### ISSUE TITLE
ntpd on the gw

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#36]
> ###### Originally posted 2015-02-08 08:46 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

We need all the machines to be time synchronized in order to use timeauth secrets. Since some machines don't have the internet, we need to setup an ntp server on the gw and configure the ntpd of the machines to use gw as their ntp server.

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-08 14:28 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Use systemd-timesyncd, see 90bc942b and a7dcbab2
