### ISSUE TITLE
Integration with ansible

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#37]
> ###### Originally posted 2015-02-08 18:57 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

A script to generate ansible hostfiles from mdb.

Set of default playbooks for:

* Notifications
* Poll
* Ping
* Service restarts
* xrandr fun
* ...

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-08 14:32 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Dynamic inventory added in 70e385d.

New issues will be created for specific tasks.
