### ISSUE TITLE
Make rfs.sh and friends stateless

### ISSUE THREAD

**Issue by Dettorer** [prologin/sadm#40]
> ###### Originally posted 2015-02-09 23:05 by [Dettorer](https://bitbucket.org/Dettorer/) on Bitbucket

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-08 20:06 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Don't waste your time on this, it won't be useful when we implement it the proper way. (See issue #64)
