### ISSUE TITLE
mdb: add a machine status field

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#41]
> ###### Originally posted 2015-02-11 14:16 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

A machine status field will help us report any problem we have with a machine to the Bocal.

Suggested fields to add:

- BooleanField is_faulty
- TextField is_faulty_details

Side issues:

- Integration with the usermap
- Display the issue on the screen if the machine is booted (integration with netboot ie. the high tech version of a post-it)

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-06 13:24 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

I suggest something more generic:

* `EnumField state {WORKING, MAINTENANCE, OUTOFORDER}`
* `TextField state_details`

As such, `is_usable ← state == WORKING`.

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-06 13:41 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

I suggest keeping it simple.

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-07 11:52 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

@seirl @Dettorer what do you think?

**Comment by Dettorer** [comment]
> ###### Originally posted 2015-04-07 12:16 by [Dettorer](https://bitbucket.org/Dettorer/) on Bitbucket

I prefer the boolean field.
Though I would rather name it "is_faulty" (for example) as the problem may not make the machine completely unusable while still needing to be reported.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-15 16:17 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Waiting for pull request #5 to be reviewed, as it introduced changes in mdb models (and migrations).

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-17 17:38 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Added in 89647ff74f32. Keeping this issue open for the side tasks.
