### ISSUE TITLE
UDBSync fail install

### ISSUE THREAD

**Issue by robin-thoni** [prologin/sadm#42]
> ###### Originally posted 2015-03-02 13:26 by [roblowchon](https://bitbucket.org/roblowchon/) on Bitbucket

When configuring udbsyncclients:
(venv)root@prologin-vm:~/sadm [master]$ python install.py udbsync_django udbsync_rootssh

[...]
Installed /var/prologin/venv/lib/python3.4/site-packages/ProloginSADM-1.0-py3.4.egg 

Processing dependencies for ProloginSADM==1.0 

Finished processing dependencies for ProloginSADM==1.0 

Copying configuration 'etc/prologin/mdbsync-pub.yml' -> '/etc/prologin/mdbsync-pub.yml.new' 

Traceback (most recent call last): 

  File "install.py", line 739, in <module> 

    requires(name) 

  File "install.py", line 679, in requires 

    globals()['install_' + component]() 

  File "install.py", line 427, in install_udbsync_django 

    requires('libprologin') 

  File "install.py", line 679, in requires 

    globals()['install_' + component]() 

  File "install.py", line 231, in install_libprologin 

    install_cfg_profile('udbsync-pub', group='udbsync') 

  File "install.py", line 160, in install_cfg_profile 

    '/etc/prologin', owner='root:%s' % group, mode=mode) 

  File "install.py", line 145, in install_cfg 

    old_contents = open(dest_path).read() 

  File "/var/prologin/venv/lib/python3.4/encodings/ascii.py", line 26, in decode 

    return codecs.ascii_decode(input, self.errors)[0] 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 845: ordinal not in range(128)

**Comment by audebert** [comment]
> ###### Originally posted 2015-03-02 13:42 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Can you post the content of your `/etc/prologin/udbsync-pub.yml`?

**Comment by robin-thoni** [comment]
> ###### Originally posted 2015-03-02 13:46 by [roblowchon](https://bitbucket.org/roblowchon/) on Bitbucket

There was a hidden char that just appeared when erasing shared_secret.
Marking as resolved.
