### ISSUE TITLE
Update python packages

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#43]
> ###### Originally posted 2015-03-02 13:58 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Packages versions are frozen in `requirements.txt`, some of them are outdated (eg. Django 1.5.1) and should be updated.

Update instructions given by each package vendor should followed with care.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-05 21:09 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Started in afc272c.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-15 07:36 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

More progress in pull request #5 (Django 1.8 mainly).

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-25 16:38 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

This should be OK now.
