### ISSUE TITLE
udb: Implement an UIDPool

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#44]
> ###### Originally posted 2015-03-31 14:36 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Just like the ``IPPool`` used by MDB, but for allocating users UID.

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-05 19:14 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

udb: add UIDPool (fix #44)


→ <<cset e74f4db0bc8f>>
