### ISSUE TITLE
Auto-fill MDB registration using LLDP

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#47]
> ###### Originally posted 2015-04-01 22:19 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Using LLDP we can know which switch the machine is connected to, and thus the RFS/HFS to be assigned to.

Patch the iPXE script so that the rfs and hfs fields are filled automatically.

**Comment by seirl** [comment]
> ###### Originally posted 2016-03-31 11:55 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Isn't that done already?

**Comment by audebert** [comment]
> ###### Originally posted 2016-04-01 16:22 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

The script is `sadm/python-lib/prologin/netboot/script.ipxe` and it works well.
We still require a patched version of ipxe for lldp support though.
