### ISSUE TITLE
concours: REST API

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#48]
> ###### Originally posted 2015-04-02 13:14 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Add a REST API for:

- Uploading champions
- Starting matches
- Getting matches status
- Starting tournaments
- Getting tournaments results

Rationnale: contestants write something similar by hand every year and lose precious time for writing an AI.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-26 21:41 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Mostly done in pull request #6 (from b252ca6).

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-29 06:56 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Merged.
