### ISSUE TITLE
firewall: use incremental updates of udb/mdb

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#49]
> ###### Originally posted 2015-04-02 13:18 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Currently ``firewall.py`` does a query to ``udb`` and ``mdb`` at each ``presenced`` update. It would be a lot better to also poll ``udb`` and ``mdb`` in order to maintain a local database of users and machines.

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-09 13:19 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

This cannot be done easily because it requires to call poll_updates() multiple times which runs forever as the main loop of the program. Maybe we should use either run_in_executor (easy) or rewrite all the code in an async fashion (hard)?

**Comment by seirl** [comment]
Done in 2a8ffe4
