### ISSUE TITLE
Use a postgresql on gw for udb, mdb and hfs/server

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#50]
> ###### Originally posted 2015-04-05 16:05 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Will enable:

- monitoring
- replication
- backup
- for ``hfs``, decoupling of the postgresql on ``web``

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-18 17:28 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Implemented in pull request #7.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-30 07:25 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Merged.
