### ISSUE TITLE
usermap: create an nginx entry and a webpage to display it.

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#51]
> ###### Originally posted 2015-04-05 17:02 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-05 20:13 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Includes #35.

**Comment by seirl** [comment]
This is done, but #35 isn't yet.
