### ISSUE TITLE
presencesync: log IP to username

### ISSUE THREAD

**Issue by Dettorer** [prologin/sadm#54]
> ###### Originally posted 2015-04-16 13:16 by [Dettorer](https://bitbucket.org/Dettorer/) on Bitbucket

Make sure that an IP address can always be linked to a user.

Technical proposition:

- Have presencesync log "{IP} claimed/released by {username}" to journald at each login/logout of a user.

**Comment by seirl** [comment]
> ###### Originally posted 2015-05-07 04:26 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

The connections are already logged in the presenced journal.
