### ISSUE TITLE
gw: log connections

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#55]
> ###### Originally posted 2015-04-16 17:59 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

The Bocal asks us to log the originator of IP traffic.

Technical proposition:

- Write a service that does something like ``conntrack -E -o timestamp -e NEW >> /var/prologin/connections.log`` but using the IPs before NAT.

**Comment by seirl** [comment]
> ###### Originally posted 2016-03-31 11:55 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

This needs of course to be connected with presenced.

**Comment by multun** [comment]
Why not using http://rlworkman.net/howtos/ulogd.html ?
Is this issue still meaningful ?

**Comment by audebert** [comment]
We implemented the conntrack service: https://github.com/prologin/sadm/blob/2017-halfr-breaks-everything/etc/systemd/system/conntrack.service
It spits a log message for every new connection.

AI to me to double check that we log the NAT and that we can track back the internal IP to a user.

**Comment by seirl** [comment]
@audebert checked it and it works well in kibana with presencesync + conntrack logs.
