### ISSUE TITLE
concours: export best matches for display

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#57]
> ###### Originally posted 2015-04-21 22:12 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

In order to steam the matches, we have to export the most interesting ones to a folder.

A match is interesting if all the players have a good number of points.

Technical propositions:

* Add a handler to concours that allow a remote user to download the n most interesting matches.

**Comment by KidoSoraKi** [comment]
> ###### Originally posted 2015-05-03 02:06 by [Kido_SoraKi](https://bitbucket.org/Kido_SoraKi/) on Bitbucket

Isn't that already done ? See [match_stream.py](https://bitbucket.org/prologin/sadm/src/44deb2eef7a7bd294445564201b47d5d7b71b176/python-lib/prologin/concours/match_stream.py?at=master#cl-25).

**Comment by audebert** [comment]
> ###### Originally posted 2015-05-04 12:58 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Is there anything else to do related to this issue?

**Comment by seirl** [comment]
> ###### Originally posted 2015-05-07 04:21 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Done, see 3a82658e1d06
