### ISSUE TITLE
Prevent exceptions when match dump does not exist

### ISSUE THREAD

**Issue by Zopieux** [prologin/sadm#59]
> ###### Originally posted 2015-05-09 12:12 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Django raises an exception, it should return a nice 404 instead. View is `MatchDumpView`.

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-07 19:22 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

concours: return 404 when match dump does not exist (fixes #59)


→ <<cset ec04d4feecb6>>
