### ISSUE TITLE
More details in the "mtype" field of mdb

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#60]
> ###### Originally posted 2015-05-14 13:18 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Currently the "mtype" field of mdb contains 3 values: user, orga and server. This is not really practical, because you can't pssh to all the netbooted machines with --mtype=orga, it also tries to pssh on external devices (laptops, phones, ...)
We should first change the values of this field with:

 - `netboot/internal/..?` for the machines we need to boot using netboot and a rhfs
 - `external/..?` for the external devices (laptops, phones, ...)
 - `server` for the server

We could then add a special field `utype` for the firewall:

- `contestant` for the contestants
- `orga` for the organizers
- `service` for the servers

**Comment by seirl** [comment]
> ###### Originally posted 2015-05-14 13:41 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

The main difference we want is actually `managed` and `unmanaged` since we can't really firewall the external devices. Maybe we could just remove the `server` and `services` fields. Is `utype` that important? Maybe to prevent contestants to log on to organizers machines?

**Comment by audebert** [comment]
> ###### Originally posted 2015-05-14 13:45 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

``utype`` enables us to select the machines to run commands. For example we only restart kdm on the users machines and leave the orga working. The field is useful, it should stay.

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-05 17:41 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Shouldn't we already know that from presenced?

**Comment by audebert** [comment]
> ###### Originally posted 2016-05-06 04:41 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Both - current user with presenced and statically defined machine purpose on mdb - are useful. For example we can conflose all the contestant machines but keep the organizer one alone, even if nobody is currently logged in those.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/60
