### ISSUE TITLE
Move toward continuous integration.

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#63]
> ###### Originally posted 2015-11-13 03:15 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Continuous integration of sadm will make sure we know as soon as something breaks. Because we try to follow the latest software updates it does quite often.

It will also help us develop major changes without the burden of installing everything from scratch each time.

What has to be done:

- Make the install process fully automated.
- Make the software easy to setup and test.
- Create a set of fixtures and scenarios to simulate a contest environment.

Each step should be fully tested.

**Comment by audebert** [comment]
> ###### Originally posted 2017-01-28 16:09 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Work update: https://bitbucket.org/halfr/sadm/commits/8e6c1b7b7d6124d9b1405ea70948c97a7c54e801

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/63
