### ISSUE TITLE
install process: refactor install scripts

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#64]
> ###### Originally posted 2015-11-13 03:40 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Currently there are multiple install scripts:

- `rfs/install.sh`
- `rfs/rfs.sh`
- `rfs/init.sh`
- `bootstrap/install_gw.sh`
- `bootstrap/install_misc.sh`

This situation is hard to maintain: what each script does and how to use them is not obvious.

Most scripts have tightly coupled the hardware setup (disk partitioning, LVM, RAID, bootloader, etc.) and software configuration steps. If theses tasks were split up we could install services in containers instead of the slow virtual machines. Doing so would help us in the continuous integration of sadm (see #63).

There are two subtasks:

- refactor the install process to avoid code duplication
- split hardware and software configuration to enable installing sadm in a container

Here is a tool that may give us ideas on how to achieve that in a simple way: https://github.com/rhinstaller/pykickstart/blob/master/docs/kickstart-docs.rst

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-07 19:13 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Idea: an HTTP server that generates installation scripts from fragments and config options. When you want to install a machine, you could do for instance: `curl http://bootstrap/rfs?raid=false` and your install script would be generated inside.

**Comment by audebert** [comment]
> ###### Originally posted 2017-01-28 16:09 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Work update: https://bitbucket.org/halfr/sadm/commits/8e6c1b7b7d6124d9b1405ea70948c97a7c54e801

**Comment by audebert** [comment]
The install process was refactored:

* Split setup in 3 categories: hardware related, generic userland and sadm
* Add container setup scripts
