### ISSUE TITLE
Document repo.prologin.org

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#68]
> ###### Originally posted 2016-04-09 21:59 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

- Update makepkg wrapper script.
- Document usage in docs/

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-01 19:53 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

* Update the docs, remove the parts about compiling packages that are already in repo.prologin.org

**Comment by audebert** [comment]
> ###### Originally posted 2017-01-28 16:00 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Documentation is in place: https://bitbucket.org/prologin/sadm/history-node/bd2c8f822111/docs/source/repo.rst?at=master
