### ISSUE TITLE
Check if user exists before creating a user.nbd

### ISSUE THREAD

**Issue by Corwind** [prologin/sadm#70]
> ###### Originally posted 2016-04-09 23:08 by [Corwind](https://bitbucket.org/Corwind/) on Bitbucket

If the user does not exist, the nbd file is created by root so the user cannot open his home when he's trying to log in.

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-05 16:56 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

hfs: check if user exists before creating its nbd (fix #70)


→ <<cset c6734be53c34>>
