### ISSUE TITLE
Numpy,Scipy,cPickle

### ISSUE THREAD

**Issue by tcosmo** [prologin/sadm#72]
> ###### Originally posted 2016-04-17 15:10 by [tsterin](https://bitbucket.org/tsterin/) on Bitbucket

Bonjour, je ne sais pas trop si ces modules sont déjà présents ça serait très chouette si ils l'étaient :

-Numpy,

-Scipy avec libblas-dev  et liblapack-dev ce qui permet d'optimiser des calculs pour theano

- cPickle : sérialisation rapide

Merci :))))

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-01 19:49 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

J'ai du mal à comprendre ce que tu vas faire avec tous ces modules, sachant que tu disposes d'environ 500ms de calcul par tour et que tu ne disposes que de très peu d'informations pour faire du machine learning intelligent. Pourrais-tu m'éclairer ?

**Comment by delroth** [comment]
> ###### Originally posted 2016-05-01 19:59 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

Numpy a des usages beaucoup plus variés que "du machine learning intelligent". Dès que tu fais des opérations sur des vecteurs/matrices en Python numpy est super pratique.

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-01 20:01 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Numpy, oui, d'ailleurs il y est déjà : https://bitbucket.org/prologin/sadm/src/3987bfe0552e31293ddc1740ac8c12317bb7bad5/rfs/contestants_package_list?at=master&fileviewer=file-view-default#contestants_package_list-165

C'est plutôt pour theano et les paquets qui vont avec que je me pose la question.

**Comment by tcosmo** [comment]
> ###### Originally posted 2016-05-02 00:20 by [tsterin](https://bitbucket.org/tsterin/) on Bitbucket

L'idée est de faire de l'apprentissage offline contre soi même sans passer
par stechec et sa limite de temps, à l'aide d'un simulateur codé maison

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-05 17:39 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

numpy, scipy et theano sont déjà présents, je ne rajouterai pas d'autres paquets pour faire du deep learning car je pense qu'ils ne sont vraiment pas adaptés au format de la finale, et que même s'ils l'étaient ça risquerait de trop désavantager les candidats qui travaillent dans d'autres langages.

**Comment by tcosmo** [comment]
> ###### Originally posted 2016-05-05 18:25 by [tsterin](https://bitbucket.org/tsterin/) on Bitbucket

Encore une fois l'apprentissage offline ne me semble pas du tout inadapté et je n ai pas l ambition de faire du deep learning, simplement d utiliser des reseaux feesfoward de base en approximation de fonctions.
Mais okok ca sera largement suffisant jpense!!

Tristan Stérin
