### ISSUE TITLE
Secret deployment automation

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#73]
> ###### Originally posted 2016-04-26 08:19 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

We don't have anything to automatically generate and deploy secret keys, and it's one of the most tedious tasks of the installation. I suggest the following system I thought about yesterday:

* Every machine we install must have a /etc/prologin/sadm-secret (root:root 0o700) containing one single shared secret (either we ask for this secret when executing install.py or we scp it from gw)
* When installing any configuration file from the etc/ folder, we match the string `%%PROLOGIN_SECRET:(?P<secret_id>\w+)%%`
* We compute `hmac(sadm_secret, secret_id) and replace it in the installed file.

We can reuse the function that performs this replacement when doing anything that needs shared secrets or passwords (SQL scripts, etc.)

multun will implement that in a separate branch so we can review it.

**Comment by seirl** [comment]
> ###### Originally posted 2016-04-26 08:20 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Paging @audebert and @delroth for reviews and comments :-)

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-04-26 08:43 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Do you think there exist doctors specialized in hmac addictions?
