### ISSUE TITLE
Add a backend for `passwd` to change your password in UDB

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#74]
> ###### Originally posted 2016-05-15 01:09 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Suggested by  Guillaume Bertholon during the 2016 final

**Comment by multun** [comment]
It does not seem to be *that* easy as pam_exec doesn't allow passing a password, so we would have to write our own pam module if we really want to add a passwd backend. Well, I guess we can also forget about pam for this very purpose, and just `alias passwd='/usr/bin/prolo_passwd'`

**Comment by Zopieux** [comment]
As a first iteration we can indeed write our own password change tool. That's easy enough, as we can tell which user is connected to which host (presenced, used by openresty/SSO).

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/74
