### ISSUE TITLE
Wallpapers for all DE/WM

### ISSUE THREAD

**Issue by Zopieux** [prologin/sadm#76]
> ###### Originally posted 2016-05-16 08:35 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

* feh for awesome/i3
* needs custom home conf for heavyweight DE eg. Plasma (or not?)

**Comment by tobast** [comment]
Although I did not backup what I did for this year's finals, I should be able to do that again pretty easily. My solution was dirty for xfce though, as it was merely replacing the stock wallpapers with a symlink to ours.

**Comment by cafehaine** [comment]
For xfce : 
https://unix.stackexchange.com/questions/173809/change-xfce-default-wallpaper-for-all-users
(basically we put another file in the skeleton)

**Comment by cafehaine** [comment]
Instead of changing user settings we could replace the default wallpapers.

For kde, the path is `/usr/share/wallpapers/Next/contents` (problem: kde seems to require the right resolutions, ie lots of `convert` is going to be needed)

For xfce, the path is `/usr/share/backgrounds/xfce/xfce-teal.jpg`

For gnome, the path is `/usr/share/backgrounds/gnome/adwaita-timed.xml` (we would need to create a custom xml to specify a unique image)

For feh, we could use `/usr/share/prologin/wallpaper.jpg` or something similar

**Comment by Zopieux** [comment]
Would symlinking all this crap to a single location (the one we put prologin stuff in) work? Except for the XML where we would put the symlink target itself.

**Comment by cafehaine** [comment]
as @multun said on irc, putting default configs in the skeleton to fetch the wallpaper for all DEs on a single file would be easier, and would make changing the wallpaper as easy as changing a single file on the nfsroot

**Comment by seirl** [comment]
For awesome:

```diff
-gears.wallpaper.maximize(wallpaper, s, true)
+gears.wallpaper.fit(wallpaper, s)
```

and:

```diff
 beautiful.init(gears.filesystem.get_themes_dir() .. "default/theme.lua")
+beautiful.wallpaper = "/var/prologin/prololo.png"
```

**Comment by seirl** [comment]
For i3:

```
exec feh --no-fehbg --bg-fill /var/prologin/prololo.png
```

We should really find a way to automate all this.

**Comment by seirl** [comment]
The `wallpaper` ansible module now takes care of this, and the `hfs_skeleton` module always uses the same location to find its wallpaper.

```
$ grep -rn '/opt/prologin/wallpaper.png'
ansible/roles/hfs_skeleton/files/skeleton/.config/plasma-org.kde.plasma.desktop-appletsrc:2:Image=/opt/prologin/wallpaper.png
ansible/roles/hfs_skeleton/files/skeleton/.config/awesome/rc.lua:45:beautiful.wallpaper = "/opt/prologin/wallpaper.png"
ansible/roles/hfs_skeleton/files/skeleton/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml:10:          <property name="last-image" type="string" value="/opt/prologin/wallpaper.png"/>
ansible/roles/hfs_skeleton/files/skeleton/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml:16:          <property name="last-image" type="string" value="/opt/prologin/wallpaper.png"/>
ansible/roles/hfs_skeleton/files/skeleton/.config/plasmarc:2:usersWallpapers=/opt/prologin/wallpaper.png
ansible/roles/hfs_skeleton/files/skeleton/.config/i3/config:153:exec --no-startup-id feh --no-fehbg --bg-fill /opt/prologin/wallpaper.png
ansible/roles/wallpaper/tasks/main.yml:9:    dest: '/opt/prologin/wallpaper.png'
ansible/roles/wallpaper/tasks/main.yml:16:    dest: '/opt/prologin/wallpaper.png'
```
