### ISSUE TITLE
sddm: fix UX annoyances

### ISSUE THREAD

**Issue by Zopieux** [prologin/sadm#77]
> ###### Originally posted 2016-05-16 08:53 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

* no way to focus the first field without using the mouse
* said fields are too small (too much padding) and it's hard to click exactly inside the editable area
* error messages do not work, see #1
* implement utmp (see their [TODO](https://github.com/sddm/sddm/wiki/TODO))
* *to be completed*

**Comment by audebert** [comment]
* keyboard layout configurations choices are loaded after the first keypress: it displays the "us" layout icon, you press a key, it instantly switches to "fr"

**Comment by seirl** [comment]
Fixed by switching to lightdm.
