### ISSUE TITLE
Automatic tournament system

### ISSUE THREAD

**Issue by Zopieux** [prologin/sadm#79]
> ###### Originally posted 2016-05-17 17:18 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Requirement list:

* ability to start tournaments manually
* ability to schedule tournaments (use celery scheduler?)
* tournament properties:
    * to be determined
* view nicely formatted results with links
* dedicated public pages in `concours/`

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-22 22:28 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

* countdown before the next tournament

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-22 22:29 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Should be merged with #23

**Comment by seirl** [comment]
Most of this was done in #128 . The "totally generic way of doing any kind of tournament" isn't there, but it's something that should be built once we have enough examples of different kinds of tournaments (that can for now be added by creating new management commands similar to `launch_roudrobin.py` and `evaluate_roundrobin.py`).
