### ISSUE TITLE
Have an interface to request an orga

### ISSUE THREAD

**Issue by delroth** [prologin/sadm#8]
> ###### Originally posted 2012-01-10 01:22 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

A user clicks the button, orgas get a notification via a daemon running on their machines.

**Comment by delroth** [comment]
> ###### Originally posted 2012-01-11 22:30 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

As said on IRC, this may be implemented by simply having a bot posting the requests on a specific IRC channel.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-15 21:26 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Started in pull request #6.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-26 14:07 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Done in pull request #6.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-29 06:56 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Merged.
