### ISSUE TITLE
Remote X11 application starting

### ISSUE THREAD

**Issue by audebert** [prologin/sadm#80]
> ###### Originally posted 2016-05-24 21:35 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Being able to remotely start quake on the contestant machine.

**Comment by tobast** [comment]
> ###### Originally posted 2017-03-02 13:42 by [tobast](https://bitbucket.org/tobast/) on Bitbucket

Isn't that simply a `DISPLAY=:0 some_command`?

**Comment by seirl** [comment]
> ###### Originally posted 2017-03-02 13:43 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

No. https://bitbucket.org/prologin/sadm/src/ddd84a37f9d3cc6100aaf43024f173e3cbc17cfb/python-lib/prologin/xhack.py?at=master&fileviewer=file-view-default

But this is an ugly hack, we should be able to do way better using xauth creds.

**Comment by audebert** [comment]
> ###### Originally posted 2017-03-05 22:01 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

I think of at least three issues once we are on the remote machine:

1. We want to connect to the X server as the target user, and from the few tests I made the `xhack.py` script should not be required anymore
2. We want to know the display's name, it's usually `:0` but we should avoid guessing it
3. We want to access the dbus session of the user, that is the content of the `DBUS_SESSION_BUS_ADDRESS` env variable

So, 1. somehow solved itself in the past year, for 2. `DISPLAY` is stored in the systemd user process and is inherited by processes started by it and for 3. we can use `machinectl shell`.

Here are a few working examples:

    # machinectl shell USERNAME@ /usr/bin/systemd-run --user /usr/bin/quake3 # Gets DISPLAY from systemd-run
    # machinectl shell USERNAME@ /usr/bin/notify-send 'Pour jouer à quake, cliquez ici' # Gets DBUS_SESSION_BUS_ADDRESS from machinectl shell

The next step is to validate theses commands and then write them into `docs/source/cookbook.rst`.

**Comment by seirl** [comment]
If this works we can also remove `xhack.py` from the repo and from setup.py

**Comment by Zopieux** [comment]
Yes please.

**Comment by tobast** [comment]
@audebert Is the ansible command you provided on IRC generic enough to fix this, with a little bit of wrapping?

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/80
