### ISSUE TITLE
HFS monitoring throws ValueError: Incorrect label count exception

### ISSUE THREAD

**Issue by Corwind** [prologin/sadm#81]
> ###### Originally posted 2017-01-28 15:31 by [Corwind](https://bitbucket.org/Corwind/) on Bitbucket

Ervery usage or call to one of the monitoring functions in hfs/server.py such as hfs_migrate_remote_user.labels(labels).observe(delta) end up thowing an exception:

ValueError: Incorrect label count

from prometheus_client/core.py

**Comment by audebert** [comment]
> ###### Originally posted 2017-01-28 15:51 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

See: https://github.com/prometheus/client_python/commit/882d5769da695bee7be5a9806b4b1d4762e23a8a

**Comment by tobast** [comment]
> ###### Originally posted 2017-03-02 13:33 by [tobast](https://bitbucket.org/tobast/) on Bitbucket

Fixed by 1a21b08
