### ISSUE TITLE
Do not hardcode IP ranges

### ISSUE THREAD

**Issue by tobast** [prologin/sadm#82]
> ###### Originally posted 2017-02-18 20:38 by [tobast](https://bitbucket.org/tobast/) on Bitbucket

The IP ranges 192.168.{0,1,250}.0/24 are hardcoded pretty much everywhere. It can get really cumbersome to install SADM using different IP ranges. You might want that eg. if you're doing a virtual installation and your home IP address is in 192.168.0.0/24 or 192.168.1.0/24; and you would like to have an IP address in the contestants' range to have an easy access to the web services.

I don't know what would be the best way to implement that, though. Maybe a configuration file somewhere, defaulting to the default ranges?

**Comment by seirl** [comment]
We now use network namespaces to circumvent this issue.
