### ISSUE TITLE
masternode RC on db updates

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#90]
There are a lot of RC with masternode.

First, sometimes the matches finish and are set to 'done' BEFORE the dispatcher sets them as pending (!!!). A hack fixes this: 2222e87a1b3b8d92b44266bdfe258da06c72b4a0

Also, sometimes matches are finished twice (after a restart for instance), and masternode updates the scores of matches already finished. We got some random empty scores.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/90
