### ISSUE TITLE
pxe: non-switch LLDP packets are used

### ISSUE THREAD

**Issue by tobast** [prologin/sadm#94]
While setting up the Masters room, I had an almost `1/2` chance of getting a LLDP packet from something else than one of the switches be used by the PXE registration script. The workarounds were either to select the correct hfs and rfs by hand, or to reboot the machine to get another LLDP packet (hopefully the right one first).

**Comment by tobast** [comment]
Partially fixed in 7d9a3cb3c7f, WiP in branch tobast-lldp

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/94
